name: enum_string_extension_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  enum_string_extension:
    path: ../enum_string_extension
  flutter:
    sdk: flutter
  json_annotation: any

dev_dependencies:
  build_runner: any
  enum_string_extension_gen:
    path: ../enum_string_extension_gen
  flutter_test:
    sdk: flutter
  json_serializable: any

dependency_overrides:
  enum_string_extension:
    path: ../enum_string_extension

flutter:
  uses-material-design: true
