name: enum_string_extension_gen
version: 1.0.0
description: Automatically generating `enumString` extensions code for classes with `@enumString` annotation.
repository: https://github.com/julienzarka/enum_string_extension
homepage: https://github.com/julienzarka/enum_string_extension/tree/master/enum_string_extension_gen
issue_tracker: https://github.com/julienzarka/enum_string_extension/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ">=1.0.0 <3.0.0"
  build: ">=2.0.0 <3.0.0"
  logging: ">=1.0.0 <2.0.0"
  source_gen: ">=1.0.0 <2.0.0"
  enum_string_extension: ">=1.0.0 <2.0.0"
#  enum_string_extension:
#    path: ../enum_string_extension

dev_dependencies:
  build_runner: ">=2.0.0 <3.0.0"
  build_test: "<3.0.0"
  test: "<2.0.0"
