name: enum_string_extension_gen
version: 0.0.1
description: Automatically generating `enumString` extensions code for classes with `@enumString` annotation.
repository: https://github.com/julienzarka/enum_string_extension
homepage: https://github.com/julienzarka/enum_string_extension/tree/master/enum_string_extension_gen
issue_tracker: https://github.com/julienzarka/enum_string_extension/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.39.0 <1.0.0"
  build: ">=1.0.0 <2.0.0"
  logging: ">=0.0.0 <1.0.0"
  source_gen: ">=0.9.0 <1.0.0"
  enum_string_extension: ">=0.0.1 <2.0.0"
  #enum_string_extension:
  #  path: ../enum_string_extension

dev_dependencies:
  build_runner: ">=1.0.0 <2.0.0"
  build_test: "<1.0.0"
  test: "<2.0.0"
